apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: demo-aareg-innsyn-arbeidsgiver
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsgiver.ekstern.dev.nav.no/arbeidsforhold
  liveness:
    path: /arbeidsforhold/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeidsforhold/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /arbeidsforhold/internal/metrics
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: http://aareg-innsyn-arbeidsgiver-api.arbeidsforhold
    - name: LOGIN_URL
      value: https://min-side-ag-fakelogin.labs.nais.io/login?issuer=selvbetjening&sub=00000000000&domain=labs.nais.io&redirect=https://arbeidsgiver.labs.nais.io/arbeidsforhold
    - name: DECORATOR_EXTERNAL_URL
      value: https://www.nav.no/dekoratoren/?context=arbeidsgiver&redirectToApp=true&level=Level4
    - name: MILJO
      value: demo
  accessPolicy:
    outbound:
      rules:
        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
      external:
        - host: www.nav.no
