apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aareg-innsyn-arbeidsgiver
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsforhold.intern.dev.nav.no/arbeidsforhold
  liveness:
    path: /arbeidsforhold/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeidsforhold/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /arbeidsforhold/internal/metrics
  tokenx:
    enabled: true
  spec:
    idporten:
      sidecar:
        autoLogin: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: https://aareg-innsyn-arbeidsgiver-api.dev-fss-pub.nais.io
    - name: LOGIN_URL
      value: https://arbeidsforhold.intern.dev.nav.no/oauth2/login?redirect=https://arbeidsforhold.intern.dev.nav.no/arbeidsforhold
    - name: DECORATOR_EXTERNAL_URL
      value: https://dekoratoren.ekstern.dev.nav.no/?context=arbeidsgiver&redirectToApp=true&level=Level4
    - name: MILJO
      value: dev
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-bruker-api
          namespace: fager
      external:
        - host: person.intern.dev.nav.no
        - host: aareg-innsyn-arbeidsgiver-api.dev-fss-pub.nais.io
        - host: dekoratoren.ekstern.dev.nav.no