apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: innsyn-aareg
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsforhold.dev.nav.no/arbeidsforhold
  liveness:
    path: /arbeidsforhold/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeidsforhold/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /arbeidsforhold/internal/metrics
  envFrom:
    - secret: innsyn-aareg
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: https://api-gw-q1.oera.no
    - name: LOGIN_URL
      value: https://loginservice.dev.nav.no/login?redirect=https://arbeidsforhold.dev.nav.no/arbeidsforhold
    - name: DECORATOR_EXTERNAL_URL
      value: https://dekoratoren.dev.nav.no/?context=arbeidsgiver&redirectToApp=true&chatbot=true&level=Level4
  accessPolicy:
    outbound:
      external:
        - host: person.dev.nav.no