apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: innsyn-aareg
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsgiver.nav.no/arbeidsforhold
  liveness:
    path: /arbeidsforhold/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeidsforhold/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /arbeidsforhold/internal/metrics
  tokenx:
    enabled: true
  envFrom:
    - secret: innsyn-aareg
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: https://api-gw.oera.no
    - name: LOGIN_URL
      value: https://loginservice.nav.no/login?redirect=https://arbeidsgiver.nav.no/arbeidsforhold
    - name: DECORATOR_EXTERNAL_URL
      value: https://www.nav.no/dekoratoren/?context=arbeidsgiver&redirectToApp=true&level=Level4
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-bruker-api
      external:
        - host: www.nav.no
