name: Deploy til dev
on:
  workflow_dispatch:


jobs:
  bygg:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy dev og demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: arbeidsforhold
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
          VAR: commit=${{ github.sha }},image=${{ steps.login.outputs.registry }}/arbeidsgiver-innsyn-aareg:${{ github.sha }}
          REF: ${{ github.sha }}

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/demo-dev-gcp.yaml
          VAR: commit=${{ github.sha }},image=${{ steps.login.outputs.registry }}/arbeidsgiver-innsyn-aareg:${{ github.sha }}
          REF: ${{ github.sha }}